# Generated by Django 4.0.4 on 2022-05-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkbookingApp', '0002_remove_ticketbooking_begining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='seat_numb',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='seat_numb',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
