# Generated by Django 4.0.4 on 2022-05-03 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tkbookingApp', '0003_alter_seats_seat_numb_alter_ticketbooking_seat_numb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketbooking',
            name='seat_numb',
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='seats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tkbookingApp.seats'),
        ),
    ]
