# Generated by Django 4.0.4 on 2022-05-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkbookingApp', '0004_remove_ticketbooking_seat_numb_ticketbooking_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketbooking',
            name='customers',
        ),
    ]
