# Generated by Django 4.0.4 on 2022-05-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkbookingApp', '0005_remove_ticketbooking_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb_phone', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
