# Generated by Django 4.0.4 on 2022-05-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkbookingApp', '0006_numb'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='numb_phone',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
