# Generated by Django 4.0.4 on 2022-05-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkbookingApp', '0007_ticketbooking_numb_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buses',
            name='type',
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='picture/%Y/%m'),
        ),
    ]
