# Generated by Django 4.0.4 on 2022-05-04 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tkbookingApp', '0009_routes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='buses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tkbookingApp.buses'),
        ),
    ]
