# Generated by Django 4.0.4 on 2022-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkbookingApp', '0010_ticketbooking_buses'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='note',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
