# Generated by Django 4.0.4 on 2022-05-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkbookingApp', '0011_ticketbooking_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seats',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
